# index:
#    path: /
#    controller: App\Controller\JobController::index

# jobOffer:
#    path: /job
#    controller: App\Controller\JobController::jobOffer
# product:
#     path: /product
#     defaults: { _controller: 'App\Controller\ProductController::index' }